server:
  port: 4040

dubbo:
  application:
    name:  rpc-consumer-1
  #连接注册中心配置
  registry:
    address: zookeeper://localhost:2181

rpc:
  version: 1.0


spring:
  application:
    name: spring-application-rpc-consumer