server:
  port: 3030

dubbo:
  application:
    name:  rpc-producer-1
  registry:
    address: zookeeper://localhost:2181
  protocol:
    check: false
    name: dubbo
    port: 23030

rpc:
  version: 1.0
spring:
  application:
    name: spring-application-rpc-producer